apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: l2gn3pdxx-python-gitops
  description: This is GitOps manifest for l2gn3pdxx-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: l2gn3pdxx-python
    backstage.io/kubernetes-id: l2gn3pdxx-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: l2gn3pdxx-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:l2gn3pdxx-python
