apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: l2gn3pdxx-python
  janus-idp.io/tekton: l2gn3pdxx-python
  backstage.io/kubernetes-id: l2gn3pdxx-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l2gn3pdxx-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
